"""Restore sync status related columns to Firewall model

Revision ID: 09fd4b75419f
Revises: cbb181d12ac1
Create Date: 2025-02-25 00:06:13.944269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fd4b75419f'
down_revision = 'cbb181d12ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_sync', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_sync_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall', schema=None) as batch_op:
        batch_op.drop_column('last_sync_error')
        batch_op.drop_column('last_sync')
        batch_op.drop_column('sync_status')

    # ### end Alembic commands ###
