"""Remove status related columns from Firewall model

Revision ID: cbb181d12ac1
Revises: 
Create Date: 2025-02-25 00:05:22.785422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb181d12ac1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firewall', schema=None) as batch_op:
        batch_op.drop_column('sync_status')
        batch_op.drop_column('last_sync')
        batch_op.drop_column('last_sync_error')

    with op.batch_alter_table('security_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_rule_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_rule_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_rule_firewall_id'), ['firewall_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_rule_last_hit'), ['last_hit'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_rule_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_rule_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_rule_vsys'), ['vsys'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_rule_vsys'))
        batch_op.drop_index(batch_op.f('ix_security_rule_seq'))
        batch_op.drop_index(batch_op.f('ix_security_rule_name'))
        batch_op.drop_index(batch_op.f('ix_security_rule_last_hit'))
        batch_op.drop_index(batch_op.f('ix_security_rule_firewall_id'))
        batch_op.drop_index(batch_op.f('ix_security_rule_enabled'))
        batch_op.drop_index(batch_op.f('ix_security_rule_action'))

    with op.batch_alter_table('firewall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_error', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('last_sync', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
